INSERT INTO
    auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    recovery_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
) values (
        '00000000-0000-0000-0000-000000000000',
        '5da34d70-9fbd-48d8-917e-2e42822529d0',
        'authenticated',
        'authenticated',
        'local@dev.com',
        crypt ('test123', gen_salt ('bf')),
        current_timestamp,
        current_timestamp,
        current_timestamp,
        '{"provider":"email","providers":["email"]}',
        '{}',
        current_timestamp,
        current_timestamp,
        '',
        '',
        '',
        ''
), (
    '00000000-0000-0000-0000-000000000000',
    '6da34d70-9fbd-48d8-917e-2e42822529d0',
    'authenticated',
    'authenticated',
    'local2@dev.com',
    crypt ('test123', gen_salt ('bf')),
    current_timestamp,
    current_timestamp,
    current_timestamp,
    '{"provider":"email","providers":["email"]}',
    '{}',
    current_timestamp,
    current_timestamp,
    '',
    '',
    '',
    ''
);
