create table public."UserPlayers" (
      id bigint generated by default as identity not null,
      created_at timestamp with time zone not null default now(),
      user_id uuid not null,
      player_id uuid not null,
      constraint UserPlayers_pkey primary key (id),
      constraint userplayers_user_player_unique unique (user_id, player_id),
      constraint UserPlayers_player_id_fkey foreign KEY (player_id) references "Players" (id) on update CASCADE on delete CASCADE,
      constraint UserPlayers_user_id_fkey foreign KEY (user_id) references "Users" (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
