create table public."TeamPlayers" (
          id bigint generated by default as identity not null,
          created_at timestamp with time zone not null default now(),
          player_id uuid not null,
          score numeric null,
          team_id uuid null,
          team_player_id text not null,
          is_score_override boolean null default false,
          constraint TeamPlayers_pkey primary key (id),
          constraint TeamPlayers_team_player_id_key unique (team_player_id),
          constraint TeamPlayers_player_id_fkey foreign KEY (player_id) references "Players" (id) on update CASCADE on delete CASCADE,
          constraint TeamPlayers_team_id_fkey foreign KEY (team_id) references "Teams" (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;
